name: orches
description: "AntiMatter - A Material 3 Expressive Task Manager App."
publish_to: 'none'
version: 1.7.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  shared_preferences: ^2.5.3
  material_color_utilities: any
  animations: ^2.0.11
  material_symbols_icons: ^4.2815.1
  dynamic_color: ^1.7.0

  settings_tiles:
    path: ./settings_tiles_custom

  expressive_loading_indicator:
    path: ./expressive_loading_indicator_modified
  custom_refresh_indicator: ^4.0.1
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home_widget: ^0.9.0
  google_fonts: ^8.0.2
  supabase_flutter: ^2.12.0
  permission_handler: ^12.0.1
  http: ^1.6.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  dio: ^5.4.0
  open_filex: ^4.5.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/flex-Regular.ttf
        - asset: assets/fonts/flex-Medium.ttf
          weight: 500
        - asset: assets/fonts/flex-Bold.ttf
          weight: 700
    - family: NotoSans
      fonts:
        - asset: assets/fonts/nato-Medium.ttf
          weight: 500
        - asset: assets/fonts/nato-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nato-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
