name: orches
description: "A Material 3 Expressive Task Manager App."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  shared_preferences: ^2.5.3
  material_color_utilities: any
  animations: ^2.0.11
  material_symbols_icons: ^4.2815.1
  dynamic_color: ^1.7.0

  settings_tiles:
    path: ./settings_tiles_custom

  expressive_loading_indicator:
    path: ./expressive_loading_indicator_modified
  custom_refresh_indicator: ^4.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
